# Generated by Django 4.1.7 on 2023-03-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0036_login_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login_model',
            old_name='constraseña',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='login_model',
            old_name='usuario',
            new_name='username',
        ),
        migrations.AddField(
            model_name='brunch_model',
            name='p1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='brunch_model',
            name='p2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='brunch_model',
            name='p3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='brunch_model',
            name='p4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='brunch_model',
            name='p5',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='brunch_model',
            name='p6',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
