# Generated by Django 4.1.7 on 2023-03-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0037_rename_constraseña_login_model_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brunch_model',
            name='p1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='brunch_model',
            name='p2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='brunch_model',
            name='p3',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='brunch_model',
            name='p4',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='brunch_model',
            name='p5',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='brunch_model',
            name='p6',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
