# Generated by Django 4.1.7 on 2023-03-27 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0038_alter_brunch_model_p1_alter_brunch_model_p2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brunch_model',
            name='p6',
        ),
    ]
