# Generated by Django 4.1.7 on 2023-04-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0042_alter_cafes_model_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populares_model',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='populares/'),
        ),
    ]
