# Generated by Django 4.1.7 on 2023-04-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0044_alter_bebidas_model_imagen_alter_brunch_model_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasteleria_model',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
