# Generated by Django 4.1.7 on 2023-04-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0045_alter_pasteleria_model_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasteleria_model',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='almendra_app/static/almendra_app/media'),
        ),
    ]
