# Generated by Django 4.1.7 on 2023-05-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0047_alter_bebidas_model_imagen_alter_brunch_model_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebidas_model',
            name='descripcion',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='cafes_model',
            name='descripcion',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='pasteleria_model',
            name='descripcion',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='salados_model',
            name='descripcion',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
