# Generated by Django 3.2.18 on 2023-09-02 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0050_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
