# Generated by Django 3.2.18 on 2023-09-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0052_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imagen',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
