# Generated by Django 3.2.18 on 2023-09-04 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0053_auto_20230904_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='imagen',
        ),
    ]
