# Generated by Django 3.2.18 on 2023-09-04 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0055_rename_imagen_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='imagen',
        ),
    ]
