# Generated by Django 4.2.5 on 2023-09-28 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0056_rename_image_product_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bebidas_model',
        ),
        migrations.DeleteModel(
            name='brunch_model',
        ),
        migrations.DeleteModel(
            name='cafes_model',
        ),
        migrations.DeleteModel(
            name='desayunos_model',
        ),
        migrations.DeleteModel(
            name='pasteleria_model',
        ),
        migrations.DeleteModel(
            name='populares_model',
        ),
        migrations.DeleteModel(
            name='salados_model',
        ),
    ]
