# Generated by Django 3.2.18 on 2023-08-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPedidos', '0002_pedidos_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos_model',
            name='tamanio_precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
