# Generated by Django 3.2.18 on 2023-08-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPedidos', '0003_pedidos_model_tamanio_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('contraseña', models.EmailField(blank=True, max_length=10, null=True)),
                ('tags', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='pasteleria_model',
        ),
    ]
