# Generated by Django 3.2.18 on 2023-08-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPedidos', '0004_auto_20230823_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_model',
            name='contraseña',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
