# Generated by Django 3.2.18 on 2023-08-24 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPedidos', '0005_alter_usuario_model_contraseña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario_model',
            name='foto_perfil',
        ),
        migrations.RemoveField(
            model_name='usuario_model',
            name='tags',
        ),
    ]
