# Generated by Django 3.2.18 on 2023-08-24 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPedidos', '0006_auto_20230823_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario_model',
            old_name='contraseña',
            new_name='contrasenia',
        ),
    ]
