# Generated by Django 3.2.18 on 2023-09-02 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPedidos', '0009_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_orderd',
            new_name='date_ordered',
        ),
    ]
