# Generated by Django 3.2.18 on 2023-09-04 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPedidos', '0014_alter_shippingaddress_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appPedidos.usuario_model'),
        ),
    ]
